package com.homeassistant.core.nlp

import com.homeassistant.core.tools.ToolCallSpec

sealed class LlmResponse {
    /**
     * Plain text completion returned by an LLM backend.
     *
     * @property content Text generated by the model.
     */
    data class Text(val content: String) : LlmResponse()

    /**
     * Tool invocation returned by an LLM backend.
     *
     * @property spec Parsed tool call name and raw arguments.
     */
    data class ToolCall(val spec: ToolCallSpec) : LlmResponse()
}
