ktor:
  deployment:
    port: 8080
    watch:
      - classes
  application:
    modules:
      - com.homeassistant.ApplicationKt.module

homeassistant:
  dbPath: "db/homeAssistant.sqlite"
  anthropicApiKey: ${ANTHROPIC_API_KEY}
  sessionTimeoutMinutes: 10
