package com.homeassistant.adapter.outbound.codex

import com.homeassistant.core.memory.MemoryType
import com.homeassistant.core.utils.JsonSerializer
import com.homeassistant.core.utils.JsonSerializer.decodeFromString
import com.homeassistant.core.utils.JsonSerializer.encodeToString
import com.homeassistant.core.utils.JsonSerializer.parseToJsonElement
import com.homeassistant.domain.topicanalysis.ClaimCertainty
import com.homeassistant.domain.topicanalysis.TopicAnalysisException
import kotlinx.schema.Schema
import kotlinx.schema.generator.json.JsonSchemaConfig
import kotlinx.schema.generator.json.SerialDescription
import kotlinx.schema.generator.json.serialization.SerializationClassJsonSchemaGenerator
import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.SerializationException
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.contentOrNull
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive

/**
 * Root object expected from the topic-analysis LLM response.
 *
 * @property topics Topics extracted from the supplied source document.
 */
@Serializable
internal data class TopicAnalysisLlmResponse(
    @property:SerialDescription("Topic candidates extracted from the source document. Return an empty array when there are no evidence-backed household memory topics.")
    val topics: List<TopicLlmResponse>,
)

/**
 * LLM-facing topic candidate before repository validation and persistence.
 *
 * @property title Short topic title generated by the LLM.
 * @property summary Review-facing topic summary generated by the LLM.
 * @property memoryTypes Memory categories represented by the topic.
 * @property domains Free-form domain tags generated by the LLM.
 * @property evidenceRecordIds Prompt-local source record ids supporting the topic.
 * @property claims Evidence-backed claims grouped under the topic.
 */
@Serializable
internal data class TopicLlmResponse(
    @property:SerialDescription("Short review-facing title for one grouped household memory topic.")
    val title: String,
    @property:SerialDescription("Concise summary of why the grouped records belong together and what household memory they may support.")
    val summary: String,
    @property:SerialDescription("Allowed MemoryType enum values represented by this topic. Use only enum values from the schema, never new labels such as PLAN, FACT, TODO, TASK, or COMMITMENT.")
    val memoryTypes: List<MemoryType>,
    @property:SerialDescription("Free-form household domain tags such as housing, moving, travel, food, or finance. Domains are topical areas, not MemoryType values.")
    val domains: List<String>,
    @property:SerialDescription("Source record ids that support this topic. Use only ids provided in the input, such as r1 or r2.")
    val evidenceRecordIds: List<String>,
    @property:SerialDescription("Evidence-backed atomic claims under this topic. Each claim must cite supporting source record ids.")
    val claims: List<TopicClaimLlmResponse>,
)

/**
 * LLM-facing claim extracted under a topic candidate.
 *
 * @property text Claim text generated by the LLM.
 * @property subject Person, place, or concept the claim is about.
 * @property memoryType Memory category assigned to the claim.
 * @property certainty How directly source evidence supports the claim.
 * @property evidenceRecordIds Prompt-local source record ids supporting the claim.
 */
@Schema
@Serializable
internal data class TopicClaimLlmResponse(
    @property:SerialDescription("Atomic memory statement supported by the cited evidence. Do not invent facts that are not observed, said, inferred, or uncertain from the source records.")
    val text: String,
    @property:SerialDescription("Person, place, object, family member, or household entity the claim is about.")
    val subject: String,
    @property:SerialDescription("Allowed MemoryType enum value for this single claim. Use only enum values from the schema, never new labels such as PLAN, FACT, TODO, TASK, or COMMITMENT.")
    val memoryType: MemoryType,
    @property:SerialDescription("How directly the source evidence supports this claim: OBSERVED for direct evidence, SAID for stated content, INFERRED for cautious inference, or UNCERTAIN when unclear.")
    val certainty: ClaimCertainty,
    @property:SerialDescription("Source record ids that support this claim. Use only ids provided in the input, such as r1 or r2.")
    val evidenceRecordIds: List<String>,
)

@OptIn(ExperimentalSerializationApi::class)
internal object TopicAnalysisOutputContract {

    val schema = SerializationClassJsonSchemaGenerator(
        json = JsonSerializer.json,
        jsonSchemaConfig = JsonSchemaConfig.Strict
    )
        .generateSchemaString(TopicAnalysisLlmResponse.serializer().descriptor)
        .inlineLocalDefinitions()

    private fun String.inlineLocalDefinitions(): String {
        val root = parseToJsonElement().jsonObject
        val definitions = root["${'$'}defs"]?.jsonObject.orEmpty()
        return root.inlineLocalReferences(definitions).encodeToString()
    }

    private fun JsonElement.inlineLocalReferences(definitions: Map<String, JsonElement>): JsonElement {
        return when (this) {
            is JsonObject -> {
                val ref = this["${'$'}ref"]?.jsonPrimitive?.contentOrNull
                if (ref != null) {
                    val referenced = definitions[ref.localDefinitionName()]
                    if (referenced != null) {
                        return JsonObject(
                            referenced.inlineLocalReferences(definitions).jsonObject +
                                this.filterKeys { it != "${'$'}ref" && it != "${'$'}defs" }
                                    .mapValues { (_, value) -> value.inlineLocalReferences(definitions) },
                        )
                    }
                }

                JsonObject(
                    filterKeys { it != "${'$'}defs" }
                        .mapValues { (_, value) -> value.inlineLocalReferences(definitions) },
                )
            }
            else -> this
        }
    }

    private fun String.localDefinitionName(): String? =
        takeIf { it.startsWith("#/${'$'}defs/") }
            ?.removePrefix("#/${'$'}defs/")
            ?.replace("~1", "/")
            ?.replace("~0", "~")

    fun decode(raw: String): TopicAnalysisLlmResponse =
        try {
            stripJsonCodeFence(raw).decodeFromString()
        } catch (error: SerializationException) {
            throw TopicAnalysisException("Failed to parse topic analysis response: ${error.message}")
        }

    private fun stripJsonCodeFence(raw: String): String {
        val trimmed = raw.trim()
        if (!trimmed.startsWith("```")) return trimmed

        val lines = trimmed.lines()
        if (lines.size < 2) return trimmed

        val bodyLines = lines.drop(1).takeWhile { it.trim() != "```" }
        return bodyLines.joinToString("\n").trim()
    }
}
