package com.homeassistant.nlp.topicanalysis.impl

import com.homeassistant.core.memory.MemoryType
import com.homeassistant.core.utils.JsonSerializer
import com.homeassistant.core.utils.JsonSerializer.decodeFromString
import com.homeassistant.datamodel.topicanalysis.ClaimCertainty
import com.homeassistant.domain.topicanalysis.TopicAnalysisException
import kotlinx.schema.generator.json.SerialDescription
import kotlinx.schema.generator.json.serialization.SerializationClassJsonSchemaGenerator
import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.SerializationException
import kotlinx.serialization.Serializable

/**
 * Root object expected from the topic-analysis LLM response.
 *
 * @property topics Topics extracted from the supplied source document.
 */
@Serializable
internal data class TopicAnalysisLlmResponse(
    @property:SerialDescription("Topic candidates extracted from the source document. Return an empty array when there are no evidence-backed household memory topics.")
    val topics: List<TopicLlmResponse>,
)

/**
 * LLM-facing topic candidate before repository validation and persistence.
 *
 * @property title Short topic title generated by the LLM.
 * @property summary Review-facing topic summary generated by the LLM.
 * @property memoryTypes Memory categories represented by the topic.
 * @property domains Free-form domain tags generated by the LLM.
 * @property evidenceRecordIds Prompt-local source record ids supporting the topic.
 * @property claims Evidence-backed claims grouped under the topic.
 */
@Serializable
internal data class TopicLlmResponse(
    @property:SerialDescription("Short review-facing title for one grouped household memory topic.")
    val title: String,
    @property:SerialDescription("Concise summary of why the grouped records belong together and what household memory they may support.")
    val summary: String,
    @property:SerialDescription("Allowed MemoryType enum values represented by this topic. Use only enum values from the schema, never new labels such as PLAN, FACT, TODO, TASK, or COMMITMENT.")
    val memoryTypes: List<MemoryType>,
    @property:SerialDescription("Free-form household domain tags such as housing, moving, travel, food, or finance. Domains are topical areas, not MemoryType values.")
    val domains: List<String>,
    @property:SerialDescription("Source record ids that support this topic. Use only ids provided in the input, such as r1 or r2.")
    val evidenceRecordIds: List<String>,
    @property:SerialDescription("Evidence-backed atomic claims under this topic. Each claim must cite supporting source record ids.")
    val claims: List<TopicClaimLlmResponse>,
)

/**
 * LLM-facing claim extracted under a topic candidate.
 *
 * @property text Claim text generated by the LLM.
 * @property subject Person, place, or concept the claim is about.
 * @property memoryType Memory category assigned to the claim.
 * @property certainty How directly source evidence supports the claim.
 * @property evidenceRecordIds Prompt-local source record ids supporting the claim.
 */
@Serializable
internal data class TopicClaimLlmResponse(
    @property:SerialDescription("Atomic memory statement supported by the cited evidence. Do not invent facts that are not observed, said, inferred, or uncertain from the source records.")
    val text: String,
    @property:SerialDescription("Person, place, object, family member, or household entity the claim is about.")
    val subject: String,
    @property:SerialDescription("Allowed MemoryType enum value for this single claim. Use only enum values from the schema, never new labels such as PLAN, FACT, TODO, TASK, or COMMITMENT.")
    val memoryType: MemoryType,
    @property:SerialDescription("How directly the source evidence supports this claim: OBSERVED for direct evidence, SAID for stated content, INFERRED for cautious inference, or UNCERTAIN when unclear.")
    val certainty: ClaimCertainty,
    @property:SerialDescription("Source record ids that support this claim. Use only ids provided in the input, such as r1 or r2.")
    val evidenceRecordIds: List<String>,
)

@OptIn(ExperimentalSerializationApi::class)
internal object TopicAnalysisOutputContract {

    val schema = SerializationClassJsonSchemaGenerator(json = JsonSerializer.json)
            .generateSchemaString(TopicAnalysisLlmResponse.serializer().descriptor)


    fun decode(raw: String): TopicAnalysisLlmResponse =
        try {
            stripJsonCodeFence(raw).decodeFromString()
        } catch (error: SerializationException) {
            throw TopicAnalysisException("Failed to parse topic analysis response: ${error.message}")
        }

    private fun stripJsonCodeFence(raw: String): String {
        val trimmed = raw.trim()
        if (!trimmed.startsWith("```")) return trimmed

        val lines = trimmed.lines()
        if (lines.size < 2) return trimmed

        val bodyLines = lines.drop(1).takeWhile { it.trim() != "```" }
        return bodyLines.joinToString("\n").trim()
    }
}

internal object TopicAnalysisPrompt {
    fun system(schema: String = TopicAnalysisOutputContract.schema): String =
        """
        주어진 source document 또는 chunk 안에서만 내용 기반으로 주제 분석하세요.
        시간 간격으로 나누지 마세요. 같은 주제가 A-B-A 순서로 중간에 끊겨도 하나의 topic으로 병합하세요.
        후보 topic은 최대 5개로 제한하세요.
        evidenceRecordIds는 topic당 최대 5개, claims는 topic당 최대 3개로 제한하세요.
        각 topic은 가족/집 second brain에 승인 후보로 올릴 수 있는 evidence-backed claim을 1개 이상 포함해야 합니다.
        evidenceRecordIds는 사용자 메시지에 제공된 r1, r2 같은 ID만 사용하세요.
        실제로 말하지 않은 사실을 확정하지 말고, 관찰/발화/추론/불확실성을 구분하세요.
        memoryType은 ${MemoryType.entries.joinToString(", ") { it.code }} 중 하나만 사용하세요.
        domain은 housing, moving, travel, food, finance 같은 생활 영역 태그이며 memoryType과 분리하세요.
        응답은 아래 JSON Schema를 준수하는 JSON object 하나여야 합니다.

        $schema
        """.trimIndent()

    fun mergeSystem(schema: String = TopicAnalysisOutputContract.schema): String =
        """
        chunk별 topic 후보 목록을 검토해 최종 topic 후보로 병합하세요.
        시간상 떨어져 있어도 같은 주제라면 하나로 병합하세요. A-B-A처럼 중간에 다른 주제가 끼어도 나누지 마세요.
        최종 최대 20개 topic으로 제한하세요.
        evidenceRecordIds는 topic당 최대 5개, claims는 topic당 최대 3개로 제한하세요.
        evidenceRecordIds는 후보 목록에 포함된 원본 r1, r2 같은 source record ID만 사용하세요.
        실제로 말하지 않은 사실을 확정하지 말고, 관찰/발화/추론/불확실성을 구분하세요.
        memoryType은 ${MemoryType.entries.joinToString(", ") { it.code }} 중 하나만 사용하세요.
        domain은 housing, moving, travel, food, finance 같은 생활 영역 태그이며 memoryType과 분리하세요.
        응답은 아래 JSON Schema를 준수하는 JSON object 하나여야 합니다.

        $schema
        """.trimIndent()
}
